### ISSUE TITLE
Typo in transfer provider org command

### ISSUE THREAD

**Issue by fpanaget** [pramodvallanur/samples#1]
Hi 
There is a typo in the `transfercatalogowner.md` at the `step 4] Initiate the transfer`
It says:
>apic org:transfer-owner --server apicserver acme transferOwner.json

should be

>apic orgs:transfer-owner --server apicserver acme transferOwner.json

**Comment by pramodvallanur** [comment]
Thanks. I assume you meant `transferproviderorgowner.md`. I have fixed and made the commit.

**Comment by fpanaget** [comment]
Yes you are correct .. it was indeed ... transferproviderorgowner.md. Thank you.
