### ISSUE TITLE
Suggestion: Place copy in ibm-apiconnect/example-toolkit-scripts

### ISSUE THREAD

**Issue by raviram203** [pramodvallanur/samples#2]
hi, Pramodh
Placing these scripts & docs https://github.com/ibm-apiconnect/example-toolkit-scripts would build a critical mass.
Ravi

**Comment by raviram203** [comment]
Please let me know if it is okay to copy specific items from your repo to https://github.com/ibm-apiconnect/example-toolkit-scripts

**Comment by pramodvallanur** [comment]
Yes pls

**Comment by raviram203** [comment]
Thanks, Pramodh.
